#-*- coding: utf-8 -*-

{
	"name": "e-wallet Inherited",
	"version": "1.0", 
	"depends": [
		'base',
		'E-Wallet'
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the e-wallet module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/sequence_deposit.xml",
		"data/sequence_transfer.xml",
		"data/sequence_withdrawal.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}