#-*- coding: utf-8 -*-

{
	"name": "e-wallet",
	"version": "1.0", 
	"depends": [
		'base',
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the e-wallet module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		# "view/partner.xml",
		# "view/bank_account.xml",
		"view/deposit.xml",
		"view/wallet.xml",
		"view/transfer.xml",
		"view/withdrawal.xml",
		"view/wallet_transaction.xml",
		# "view/currency.xml",
		"report/partner.xml",
		"report/bank_account.xml",
		"report/deposit.xml",
		"report/wallet.xml",
		"report/transfer.xml",
		"report/withdrawal.xml",
		"report/wallet_transaction.xml",
		"report/currency.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}